### PR TITLE
Issue 743 quick fix hw crc32 capability check on arm64

### PR DESCRIPTION
**Pull request by sergey-dryabzhinsky**
For #743 

Just check if `HWCAP_CRC32` ever defined after including `sys/auxv.h`

### CODE REVIEW

**Comment by dormando** [comment]
Thanks! I'll see if it's worth adding that define if missing too.

**Comment by sergey-dryabzhinsky** [comment]
I think it should not be custom defined since gcc-4.8 has partial arm64 support.
AFAIK hw crc32 available on ARM8.1.
So it's fine if memcached safely builds w/o hw crc32 on such old distros.

**Comment by sergey-dryabzhinsky** [comment]
But maybe it should be checked by autotools if possible.

**Comment by dormando** [comment]
Note to self: looks like the user's repo is gone. need to recover the change manually.

**Comment by dormando** [comment]
Out in 1.6.10

**Pull request closed without merging**
