### PR TITLE
modify slab_automove_extstore delete a->window_global

### PR DESCRIPTION
**Pull request by whynotAC**
modify Memory leak by a->window_global

### CODE REVIEW

**Comment by dormando** [comment]
nice, thanks!

**Comment by whynotAC** [comment]
What else do I need to do for this merger?

**Comment by whynotAC** [comment]
I want to write an analysis article about memcached, you need to look at the code to understand the overall framework design. Do you have any good ideas to help me complete the analysis?
I intend to start from the following aspects:
Slab manager
Hash manager
Lru manager
Work manager
And so on

At the moment I have only completed some of the analysis and still need a lot of work to do.

**Comment by dormando** [comment]
don't think so. I merge small fixes like this closer to release time.

https://memcached.org/blog/ has a number of articles about memcached internals, including the LRU. haven't written anything recent about slab and worker threads haven't changed in over a decade.

**Comment by whynotAC** [comment]
thanks

**Comment by dormando** [comment]
out in 1.5.15, thanks!

**Pull request closed without merging**
