### PR TITLE
fixes with clang compiler

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by dormando** [comment]
Thanks!

**Comment by debohman** [comment]
Which version of clang are you using?

**Comment by kraj** [comment]
clang-15, but it was before the error were turned back into warnings since it was delayed till clang-16.

**Comment by debohman** [comment]
So, are you building with a final release of clang-15? Because, memcached-1.6.17 does not build for me using clang-15.0.2. The build has:
```
clang -Wall -Werror -pedantic -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls
```

**Comment by dormando** [comment]
released in 1.6.18

**Pull request closed without merging**
