### PR TITLE
Ensure t/whitespace.t dies with a good error outside valid git checkouts

### PR DESCRIPTION
**Pull request by terabyte**
Greetings!  I'm trying to familiarize myself with the memcached codebase so I thought I'd try to bang out a few easy "help wanted" issues.  Please let me know if there is anything I can change to get this PR accepted.  Thanks!

The test as written uses git to find a list of files to check, so it doesn't
work correctly outside a git checkout.

Reported in #485

### CODE REVIEW

**Comment by dormando** [comment]
Thanks!

Close! If you put the die there, the test will simply fail when run outside of a git repo (like a tarball download). If you look a few lines below at the skip_all + exit, that's what you have to repeat there.

Normally if git isn't even installed or you're not in a git repo at all it will properly skip the tests. The bug is when people unroll a memcached tarball inside something else that has a git repo, so git ls-files works and it dies processing the wrong data. So we just need the extra skip_all if the git directory isn't local.

**Comment by terabyte** [comment]
Ah, that makes sense!  Is this more like what you had in mind?  Sorry if this is more work than you just doing it =)

**Comment by terabyte** [comment]
Erm, minor typo, re-uploading in a sec after I've tested more carefully locally.

**Comment by terabyte** [comment]
Tested locally with and without a .git directory:

    t/whitespace.t .............. skipped: Skipping test because this does not appear to be a memcached working directory

**Comment by dormando** [comment]
message should probably say something about git :)

skips properly when the git dir is one below the base directory?

**Comment by terabyte** [comment]
Yes, it checks that the .git directory specifically exists in "$Bin/../.git".  We could try to be even fancier by calling something like:

     $ git rev-parse --show-toplevel
    /home/cmyers/projects/memcached

And then doing some rel2abs directory math... Also maybe we could just run git commands to see if it "looks like" a memcached git checkout somehow?  Open to ideas on how that might work.  I wrote this change assuming that if the .git directory is in the right "level", it is probably correct.

**Comment by dormando** [comment]
Doesn't need to be fancy; just confirming you tested the original condition :) I'll give it a local test and queue it up for the next branch when I swing back for a merge down.

**Comment by dormando** [comment]
out in 1.5.21, thanks!

**Pull request closed without merging**
