### PR TITLE
Metadump segfault

### PR DESCRIPTION
**Pull request by dormando**
Fix for #229 (and a second one I spotted).

Error handling was so close on this one :) Turned out to be easy to reproduce; which is weird, was fairly sure I tested this code path. Need a better method of extending the unit tests for it.

### CODE REVIEW

**Comment by VictorYYW** [comment]
Hi, dormando! I am an undergraduate student doing research on various bugs. Could you please show me the way to reproduce this bug? (the original issue report mentioned _key iteration_ which I can't understand.)

**Comment by dormando** [comment]
@VictorYYW `lru_crawler metadump all` is a command used to asynchronously list item metadata for everything in the cache. It's used for debugging, copying, analysis, etc.

The repro is to load a few thousand/million items into a cache server, run the metadump command, then disconnect the client without reading the results. It'll try deref a null pointer to find the client since metadump wasn't stopping.

**Comment by VictorYYW** [comment]
That make a lot of sense! Thank you, @dormando !

**Comment by VictorYYW** [comment]
Hi, @dormando ! I am still trying to reproduce this bug. I tried to set 9998 key-value pairs and run the metadump command. But the output immediately shows up in the console before I could disconnect the connect. Any hint on how I can "disconnect the client without reading the results".

**Comment by dormando** [comment]
load a million keys.

**Comment by VictorYYW** [comment]
But even after loading 9998 keys, the metadump command only gives around 6000 items. Do you think I should set up more memory when starting the memcached server?

**Comment by dormando** [comment]
set smaller (0 byte) values and/or give the instance more RAM, yes.

**Comment by VictorYYW** [comment]
I am trying to load that many keys into memcached. It's gonna take a long time. Hope that would work. Thank you for your explanation!

**Comment by dormando** [comment]
https://github.com/memcached/mc-crusher/blob/master/bench-warmer

**Comment by VictorYYW** [comment]
That seems to be exactly what I want. You are really helpful! However, when I tried to run the perl script with argument like
```./bench-warmer 127.0.0.1 key 0 1000000```
It seems that four arguments is parsed correctly.(exit on line 17) I verified that the arguments should have been parsed by printing out their value. Besides, I have done some researches on perl since I am totally new to it. If you still have time to look into it, I will very appreciate it.

**Comment by dormando** [comment]
`./bench-warmer 127.0.0.1:11211 key 0 1000000`
you forgot the port, probably?

**Comment by VictorYYW** [comment]
Actually, I have tried to append the port at the very beginning. Unfortunately, it exited with same error.

**Comment by dormando** [comment]
what error?  you didn't list one in your comment

**Comment by VictorYYW** [comment]
Oh, I am sorry. I should have made it clear. It exit at this line
```die "bench-warmer addr prefix size count" unless $addr && $prefix && $size && $count;```
So, I guess it should be the problem that the arguments are parsed properly.

**Comment by dormando** [comment]
heh. set size to 1 instead of 0. dumb bug on my part, I never run it with less than 8. should be checking for defined instead of simply true..

**Comment by VictorYYW** [comment]
Oh, that works. One last question (sorry for asking so many dump questions). How can I simulate the process of close connection before reading?
I tried `echo "lru_crawler memadump all" | nc 127.0.0.1 11211`as well as
establishing connection with telnet, try `lru_crawler metadump all`, use `^]` to escape and `quit`.
But both method can't resulting in segmentation fault of memcached.

**Comment by dormando** [comment]
That's all I did to reproduce it. are you testing the correct version?

otherwise you can write a small program that connects, runs the command, then disconnects without calling any read's. or try loading even more items (5-10 million)

**Comment by VictorYYW** [comment]
What do you mean by "calling reads"?

**Comment by dormando** [comment]
The read() syscall.

**Comment by VictorYYW** [comment]
I tried to use gdb on telnet to break before any read's. But in that case, `lru_crawler metadump all` gives no output and even `^]` or `^c` or `^d` can't help me escape the program or gdb. Am I missing anything?

**Comment by dormando** [comment]
I'm a little lost. The bug was trivial to reproduce by loading a 1 million keys the ^C'ing a netcat. are you testing against the wrong version of memcached? the bug was patched months ago.

**Comment by VictorYYW** [comment]
You are right! The bug should be reproduced easily. I made a very silly mistake when I was using docker to reproduce this bug. I simply forgot that memcached server is running in the background, so the error message will not show up in the console.

Thanks a lot, @dormando ! Really appreciate your time!

**Pull request merged**
