### PR TITLE
log: fix race condition while incrementing log entries dropped

### PR DESCRIPTION
**Pull request by rtadepalli**
This fixes the bug reported in #885 

Looks like the reporter didn't make a patch, and the issue has been open for a while, so I took the liberty to make a PR.

### CODE REVIEW

**Comment by rtadepalli** [comment]
@dormando please let me know if this PR needs to be against `next`. Thanks.

**Comment by dormando** [comment]
Ah heh. sorry. I am terminally behind on issues. Thanks!

Shouldn't need to rebase it against next since it's trivial.

**Comment by rtadepalli** [comment]
Ha, just saw that this is PR number 1000. That's exciting!

**Comment by dormando** [comment]
Congrats :) I'd offer to send you some ancient merch but I have no idea where it all went.

**Comment by rtadepalli** [comment]
Are there some other tasks that need to be run? Looks like the only check that ran was the build test.

**Comment by dormando** [comment]
That's it. I have a bunch of buildbots but they're on my end of things, the github test is just a quick pass to make sure it builds and runs basic tests. I've got a big queue of small PR's to go through in some order..

**Comment by rtadepalli** [comment]
Got it. I was going to ask if this could be merged, but a queue makes sense. Looking forward to getting my first contribution in! Thanks.

**Comment by dormando** [comment]
Out in 1.6.19

**Pull request closed without merging**
