### PR TITLE
stats_prefix: Remove test failure due to non-determinism

### PR DESCRIPTION
**Pull request by kanak**
If you have multiple keys, the order in which they are dumped is
non-deterministic because it is iterating over a hash table used by
prefix stats.

Fix the assertions by searching for expected lines in output instead
of checking that the strings are exactly the same.

### CODE REVIEW

**Comment by dormando** [comment]
Shoot. This doesn't apply to `next`, can you fix?

**Comment by kanak** [comment]
Rebased against next and fixed the conflict. Also changed the target of this pull request to "next" instead of "master" so that it doesn't show that there are 1500 lines changed :)

**Comment by dormando** [comment]
all merged up, thanks!

**Comment by dormando** [comment]
out in 1.6.0!

**Pull request closed without merging**
