### PR TITLE
Mac M1 build update.

### PR DESCRIPTION
**Pull request by devnexen**
detects arm64 crc32 h/w support.

### CODE REVIEW

**Comment by dormando** [comment]
thanks!

**Comment by dormando** [comment]
Nuts. I briefly had an m1 mac and forgot to validate this before returning it :(

**Comment by ssewell** [comment]
I had to cherry pick stats_prefix.c and stats_prefix.h from the master branch, but this builds and executes fine on my M1 MacBook Air.

**Comment by dormando** [comment]
@devnexen mind rebasing this?

**Comment by dormando** [comment]
released in 1.6.17

**Pull request closed without merging**
