### PR TITLE
Adding unit tests for watch deletions when calling mcp.internal()

### PR DESCRIPTION
**Pull request by YufeiHu**
The `watch deletions` command is not printing the deletion logs correctly when sending deletion requests through `mcp.internal()`. The attached unit test file illustrates this issue.

### CODE REVIEW

**Comment by dormando** [comment]
Thanks!

**Comment by dormando** [comment]
@YufeiHu 

Thanks! Any chance you could integrate this test into `t/proxyinternal.t` instead of having it be its own file? If not I'll do it; but just offering in case you feel up to contributing.

That test is listening on CMD_ANY so it should be pretty trivial to add the watcher bits as a subtest

**Comment by YufeiHu** [comment]
@dormando 

I've addressed the suggestion! The test now passes after I applied the same fix as in your branch (https://github.com/memcached/memcached/pull/1178).

If there are any further adjustments needed, I’ll take care of them promptly. Thanks!

**Comment by dormando** [comment]
Looks rad, thanks!

I need to port more of these test files to the object based one though, sorry!

**Comment by dormando** [comment]
merged

**Pull request closed without merging**
