### PR TITLE
Rewrite memchached-tool 'dump' method to use new lru_crawler interface.

### PR DESCRIPTION
**Pull request by calin-iorgulescu**

### CODE REVIEW

**Comment by calin-iorgulescu** [comment]
Should also solve #335 .

**Comment by dormando** [comment]
nice. will take a look when I can. really regretting not adding a run limit to the lru_crawler command :(

**Comment by dormando** [comment]
tabs in the file (see t/whitespace.t failure), devtools/clean-whitespace.pl can fix.

isn't dumping 0 exptime values, since regex is matching (\d+) and they're dumped with "-1".

slightly nervous since there's no cap to the amount of items being dumped, buffering the keys in memory is going to go poorly for people. might be okay, but perhaps a dump limit default/option would be prudent.

**Comment by calin-iorgulescu** [comment]
Argh, missed the whitespaces, sorry about that. Changed the commit, whitespace tests pass now. I also fixed the regex to catch the `-`.

Would limiting the number of items fetched from `memcached-tool` suffice? Or are you considering parametrizing `lru_crawler metadump` s.t. only the first `limit` keys are returned?

**Comment by dormando** [comment]
Yeah counting rows would suffice, but you have to disconnect and reconnect to stop the dump and start fetching stuff... I do need to actually parameterize lru_crawler commands but that's going to be painful.

I can accept it as is and can adjust again in the future though.

**Comment by calin-iorgulescu** [comment]
Wrote a quick draft of what this might look like, feedback welcome. Please see f0e30ae.

**Comment by dormando** [comment]
Looks fine to me. just add a comment for why the close is there (and to revisit in the future when the correct parameter appears)?

**Comment by dormando** [comment]
was there anything in particular you are concerned about with your change? I just tested it and it works fine too

**Comment by calin-iorgulescu** [comment]
Nothing in particular, thanks for looking it over! Added a comment as suggested, and also added a brief description to the `memcached-tool` manpage.

**Comment by dormando** [comment]
rad. thanks for the docs update!

**Comment by dormando** [comment]
released in 1.5.7

**Pull request closed without merging**
