### PR TITLE
unit tests couple of memory leak fixes proposals.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by martin-g** [comment]
Looks related to https://github.com/memcached/memcached/pull/588

**Comment by devnexen** [comment]
Ah if there is already a fix planned for those forget my PR then ;-)

**Comment by martin-g** [comment]
No, #588 revealed that there are problems in testapp. So your PR comes just in time! :-)

**Comment by dormando** [comment]
Thanks!

**Comment by dormando** [comment]
out in 1.6.0!

**Pull request closed without merging**
