### PR TITLE
Documentation build fixes

### PR DESCRIPTION
**Pull request by olajep**
Tried to break this into two pulls but the second patch depends on the first.

### CODE REVIEW

**Comment by olajep** [comment]
(Force push was converting rfc2629.dtd from CRLF to CR, didn't show up in vimdiff)

**Comment by dormando** [comment]
thanks!

**Comment by dormando** [comment]
No way to automatically get the list of .txt files? There's no way I/others are going to remember to update that list, and new files do occasionally land there.

**Comment by dormando** [comment]
Thanks!

**Comment by dormando** [comment]
I'm releasing this anyway, but this breaks `make dist` if xml2rfc and xsltproc aren't installed. `@XML2RFC@` gets set to 'no' and it tries to run... `no`. If you have some time to fix in another PR, would be appreciated. At least give a better error than not being able to find the `no` command :)

**Comment by dormando** [comment]
this also leaves some files that aren't .gitignored or cleaned up properly:
```
	doc/protocol-binary-range.full
	doc/protocol-binary.full
```

unfortunately my buildbots don't test... the release process... I guess..

**Comment by dormando** [comment]
Out in 1.5.20

**Pull request closed without merging**
