### PR TITLE
Adding FreeBSD capabilities support.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by dormando** [comment]
Thanks!

This looks pretty bare. Does it actually pass tests?

**Comment by devnexen** [comment]
Similarly as OpenBSD on this matter.

**Comment by devnexen** [comment]
Any chance those BSD PR got merged ? :-)

**Comment by dormando** [comment]
sorry for the long wait! This finally went into the 'next' branch. What versions of FreeBSD does this work on? My builder doesn't currently work so it's not easy for me to test myself.

**Comment by devnexen** [comment]
FreeBSD capsicum is even supported by FreeBSD 9.3 which is no longer supported since 2014 so it is pretty safe :-)

**Comment by dormando** [comment]
out in 1.5.14

**Pull request closed without merging**
