### PR TITLE
Disable bad memory test on Darwin.

### PR DESCRIPTION
**Pull request by devnexen**
Might be kernel issue but the signal isunfortunately not discarded.

### CODE REVIEW

**Comment by dormando** [comment]
think I pulled out the UMEM compat from cache.c? so can probably drop that entirely.

**Comment by devnexen** [comment]
even better :-)

**Comment by dormando** [comment]
Ah I did must've parsed this backwards. I removed the UMEM stuff, which means that test is relevant.

Can you fix the test properly? Or at least write up what's going wrong in more detail, what version of OS X, etc. Doesn't seem like this is failing for other OS X builds.

**Comment by devnexen** [comment]
Well ... I can t reproduce anymore. The redzone test which raises an abort does but the the custom signal handler was not triggered. seems with last mac update it s gone (do not know if this is really related tough).

**Pull request closed without merging**
