### PR TITLE
Add include stdio.h to restart.c

### PR DESCRIPTION
**Pull request by minkikim89**
Compile error occur..
```
restart.c: In function ‘restart_check’:
restart.c:75:5: error: implicit declaration of function ‘fopen’ [-Werror=implicit-function-declaration]
     FILE *f = fopen(metafile, "r");
     ^
restart.c:75:15: error: initialization makes pointer from integer without a cast [-Werror]
     FILE *f = fopen(metafile, "r");
               ^
restart.c:77:9: error: implicit declaration of function ‘fprintf’ [-Werror=implicit-function-declaration]
         fprintf(stderr, "[restart] no metadata save file, starting with a clean cache\n");
         ^
restart.c:77:9: error: incompatible implicit declaration of built-in function ‘fprintf’ [-Werror]
restart.c:77:17: error: ‘stderr’ undeclared (first use in this function)
         fprintf(stderr, "[restart] no metadata save file, starting with a clean cache\n");
                 ^
restart.c:77:17: note: each undeclared identifier is reported only once for each function it appears in
restart.c:89:9: error: incompatible implicit declaration of built-in function ‘fprintf’ [-Werror]
         fprintf(stderr, "[restart] corrupt metadata file\n");
...
```

restart.c source code need to include stdio.h .

### CODE REVIEW

**Comment by dormando** [comment]
Weird. What OS/OS version/compiler version do you have?

**Comment by minkikim89** [comment]
I have CentOS7.6 and gcc version 4.8.5
FYI, if I compile with 'enable-tls', it is compiled normally.

**Comment by dormando** [comment]
Thanks! I've made this mistake at least one other time recently, but none of my 6+ buildbots throw a compile error here. need to add this centos one.

**Comment by dormando** [comment]
out in 1.5.19!

**Pull request closed without merging**
