### PR TITLE
proxy: replace old proxy.t tests with proxyunit tests

### PR DESCRIPTION
**Pull request by FinnitoProductions**
### Background 
The tests in `proxy.t` follow a different approach to most of the other tests in the proxy testing suite in that they spin up real memcached instances as backends instead of mocking the backends out as is done in `proxyunits.t`. As a result, the `proxy.t` tests can be rather brittle and lack isolation. For instance, if a port intended for use by one of the real backends is already in use on the given development machine, these tests will fail locally even if the implementation itself is perfectly correct. 

### Summary
This PR ports all tests in `proxy.t` to equivalent versions in `proxyunits.t` and deprecates the `proxy.t` file.

### Tests
| Lines in `proxy.t`    |  Equivalent Lines in `proxyunits.t` |
| ----------- | ----------- |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L1-L55   | N/A: setup       |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L56-L59   | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L310-L328        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L60-L66   |  https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L469-L475        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L67-L77   | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L477-L483        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L78-L83   | **NEW** https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L407-L413        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L84-L90   | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L310-L317        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L91-L107  | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L397-L405 https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L415-L423 |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L108-L113   | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L443-L450        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L114-L116  |  **NEW** https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L434-L441        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L117-L135  | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L387-L395  https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L425-L432        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L136-L149  | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L379-L385        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L150-L165  | N/A: Attempted to replicate passing in newline without carriage return, but backend kept returning "SERVER_ERROR backend failure."        |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L166-L171 | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L310-L317 |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L172-L178 | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L461-L467 |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L179-L184 | https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L443-L450 |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L185-L191 | **NEW** https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L452-L459  |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L192-L202 | **NEW** https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L330-L355 |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L203-L220 | **NEW** https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L319-L328 |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L221-L230 | **NEW** https://github.com/memcached/memcached/blob/422e3c098fbbb26e22e75fb3c99e25409ad5239f/t/proxyunits.t#L367-L377 |
| https://github.com/memcached/memcached/blob/ae7d00a2464e1ba7c6216aa6afe5650d9d28313f/t/proxy.t#L231-L264 | N/A: subroutines and helper functions |

### CODE REVIEW

**Review by FinnitoProductions — COMMENTED** [review]
Hi @dormando, this PR is ready for review -- I have confirmed that the test suite passes, and I have squashed all changes into one commit. 

To be sure that all the deleted tests have equivalents in  `proxyunits.t`, I created a line-by-line breakdown in the "Tests" section of the PR description showing how each section of `proxy.t` has a corresponding section in `proxyunits.t`. Further, to justify each of the new proxyunit tests that I added (6 total), I provided a PR comment for each of them linking back to their corresponding original (now-deleted) test in `proxy.t`. 

Let me know if there's anything I've missed! Thanks

**Comment by dormando** [comment]
I think the change looks fine, but your description is misattribution. All of the other tests actually use tcp listener ports and will potentially fail if you have something listening on those ports already, not just this one. Your system has some other issue wrong with it.

The reason why we don't want to use a bunch of real servers is just to get better end to end control and validation. We can validate what the backend receives and then what what the client receives. When testing against a "real" server we might not know if the backend is being accidentally accommodating to bad or crossed syntax.

**Comment by dormando** [comment]
merged to `next`, thanks!

**Comment by dormando** [comment]
released in 1.6.22

had to fix a few warning emissions with this.

**Pull request closed without merging**
