### PR TITLE
Improve Get And Touch documentation

### PR DESCRIPTION
**Pull request by andreazevedo**
Just fixing the "underlining" of the "Get And Touch" section.

### CODE REVIEW

**Comment by dormando** [comment]
Hello there! :)

merged into the 'next' branch, thanks!

**Comment by ushuz** [comment]
@dormando FYI, you can change pull request's base branch to take advantage of github's merge functionality
https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by dormando** [comment]
@ushuz I know how github works :) I use commandline tooling to manage most of my interaction with github, leaving the PR's/issue's open until the actual release is cut. Mostly a personal preference.

**Comment by dormando** [comment]
sorry, took a break from monthly cuts for a while. this actually went out with 1.5.13 :) You should fix a few more of these issues!

**Pull request closed without merging**
