### PR TITLE
Fix dtrace probe 1.6.0

### PR DESCRIPTION
**Pull request by shivnagarajan**
with the refactoring in https://github.com/memcached/memcached/commit/b2cadc45dfb514ef16c3353abe18845f146dfb2b the dtrace hook no longer can reference `c->wbuf` and `c->wbytes`. 

We build with `--with-dtrace` and the errors are essentially 

```

[2020-03-10T12:55:49Z] In file included from memcached_dtrace.h:19,
--
  | [2020-03-10T12:55:49Z]                  from trace.h:5,
  | [2020-03-10T12:55:49Z]                  from memcached.h:798,
  | [2020-03-10T12:55:49Z]                  from memcached.c:16:
  | [2020-03-10T12:55:49Z] memcached.c: In function 'conn_set_state':
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached_dtrace.h:138:1: error: first argument to '__builtin_choose_expr' not a constant
  | [2020-03-10T12:55:49Z]   138 \| DTRACE_PROBE3 (memcached, process__command__end, arg1, arg2, arg3)
  | [2020-03-10T12:55:49Z]       \| ^~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached_dtrace.h:138:1: error: first argument to '__builtin_choose_expr' not a constant
  | [2020-03-10T12:55:49Z]   138 \| DTRACE_PROBE3 (memcached, process__command__end, arg1, arg2, arg3)
  | [2020-03-10T12:55:49Z]       \| ^~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached_dtrace.h:138:1: error: first argument to '__builtin_choose_expr' not a constant
  | [2020-03-10T12:55:49Z]   138 \| DTRACE_PROBE3 (memcached, process__command__end, arg1, arg2, arg3)
  | [2020-03-10T12:55:49Z]       \| ^~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:54: error: 'conn' {aka 'struct conn'} has no member named 'wbuf'; did you mean 'rbuf'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                      ^~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached_dtrace.h:138:1: error: first argument to '__builtin_choose_expr' not a constant
  | [2020-03-10T12:55:49Z]   138 \| DTRACE_PROBE3 (memcached, process__command__end, arg1, arg2, arg3)
  | [2020-03-10T12:55:49Z]       \| ^~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached_dtrace.h:138:1: error: first argument to '__builtin_choose_expr' not a constant
  | [2020-03-10T12:55:49Z]   138 \| DTRACE_PROBE3 (memcached, process__command__end, arg1, arg2, arg3)
  | [2020-03-10T12:55:49Z]       \| ^~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached_dtrace.h:138:1: error: first argument to '__builtin_choose_expr' not a constant
  | [2020-03-10T12:55:49Z]   138 \| DTRACE_PROBE3 (memcached, process__command__end, arg1, arg2, arg3)
  | [2020-03-10T12:55:49Z]       \| ^~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:63: error: 'conn' {aka 'struct conn'} has no member named 'wbytes'; did you mean 'rbytes'?
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|                                                               ^~~~~~
  | [2020-03-10T12:55:49Z] memcached.c:971:13: note: in expansion of macro 'MEMCACHED_PROCESS_COMMAND_END'
  | [2020-03-10T12:55:49Z]   971 \|             MEMCACHED_PROCESS_COMMAND_END(c->sfd, c->wbuf, c->wbytes);
  | [2020-03-10T12:55:49Z]       \|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~


```

Without this fix.

@dormando

### CODE REVIEW

**Comment by dormando** [comment]
Thanks! what's your platform?

**Comment by shivnagarajan** [comment]
This was just docker, alpine

**Comment by dormando** [comment]
Thanks.

**Comment by dormando** [comment]
out in 1.6.1!

**Pull request closed without merging**
