### PR TITLE
sock ip filtering tagging support for FreeBSD

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by dormando** [comment]
Thanks!

Can you add more detail about what this is for? The help argument doesn't say anything about FreeBSD or what it's for.

**Comment by devnexen** [comment]
with ipfw (ip filtering) you can redirect some packets with a ID of your choosing.

**Comment by devnexen** [comment]
so what do you think ? I could not find anything close on Linux.

**Comment by dormando** [comment]
Looks like you figured out linux/openbsd. I'm still not sure of the use case. I understand what it does but nobody's ever asked for this before. was this something you actually make use of?

**Comment by devnexen** [comment]
In some corner cases it might be useful, in my case I have a box with particular firewall rules.

**Comment by dormando** [comment]
released in 1.6.17

**Pull request closed without merging**
