### PR TITLE
Fix typos in doc/code comments (tem->item, etc)

### PR DESCRIPTION
**Pull request by TysonAndre**

### CODE REVIEW

**Review by 4383 — APPROVED** [review]
LGTM

**Comment by dormando** [comment]
Mind dropping the changes to crc32c.c? that's an upstream files and that just makes merge conflicts if I ever need to update it again :) Rest look good.

**Comment by TysonAndre** [comment]
> Mind dropping the changes to crc32c.c? that's an upstream files and that just makes merge conflicts if I ever need to update it again :) Rest look good.

Done

**Review by 4383 — APPROVED** [review]

**Comment by dormando** [comment]
released in 1.6.11

**Pull request closed without merging**
