### PR TITLE
core: add --enable-large-client-flags

### PR DESCRIPTION
**Pull request by dormando**
turns client flag handling for text protocols from 4 bytes to 8 bytes.

TODO:
- [x] specific tests.
- [x] see about disabling or hobbling binprot
- [x] need some kind of stats output somewhere indicating size

@feihu-stripe

### CODE REVIEW

**Comment by feihu-stripe** [comment]
LGTM, thanks for making it happen.

**Review by feihu-stripe — APPROVED** [review]

**Comment by dormando** [comment]
ready to merge pending any extra validation. not planning on personally doing a lot of work here.

**Review by FinnitoProductions — APPROVED** [review]
Hi @dormando, I performed end-to-end validation of these changes, and all looks good to me. I executed a sequence of commands on a proxy node communicating with multiple backends, first with the flag not provided in `configure` and then with the flag provided in `configure`, for the binaries on both the proxy node and the backend nodes. 

I tested that the following client flag tokens could be persisted by backends and retrieved:
- 748923
- 2^32 
- (3 * 2^32) + 2
- 2^64 - 1

I additionally tested that 2^64 resulted in a command-line error in both instances.

### Test 1: No Large Client Flags
#### Proxy Configuration 
`./configure --prefix=/usr/local/memcached --enable-proxy --enable-tls`
#### Backend Configuration
`./configure --prefix=/usr/local/memcached --enable-tls`
#### Results
```python
mg /testnamespace/1 v c N100
VA 5 c123214
abcde

ms /testnamespace/1 5 C123214 F748923 
abced  
HD

mg /testnamespace/1 v c N100 f
VA 5 c124376 f748923
abced

ms /testnamespace/1 5 C124376 F4294967296 # 2^32                
test1
HD

mg /testnamespace/1 v c N100 f
VA 5 c125714 f0
test1

ms /testnamespace/1 5 C125714 F12884901890 # (3 * 2^32) + 2
test9
HD

mg /testnamespace/1 v c N100 f
VA 5 c129225 f2
test9

ms /testnamespace/1 4 C129225 F18446744073709551615  # 2^64 - 1                            
data
HD

mg /testnamespace/1 v c N100 f
VA 4 c217476 f4294967295
data

ms /testnamespace/1 3 C217476 F18446744073709551616 # 2^64
abc
CLIENT_ERROR bad command line format

mg /testnamespace/1 v c N100 f
VA 4 c217476 f4294967295
data
```

### Test 2: Large Client Flags
#### Proxy Configuration 
`./configure --prefix=/usr/local/memcached --enable-proxy --enable-tls --enable-large-client-flags`
#### Backend Configuration
`./configure --prefix=/usr/local/memcached --enable-tls --enable-large-client-flags`
#### Results
```python
mg /testnamespace/1 v c N100
VA 0 c11573 W

ms /testnamespace/1 5 C11573 F748923
abced
HD

mg /testnamespace/1 v c N100 f
VA 5 c12485 f748923
abced

ms /testnamespace/1 5 C12485 F4294967296 # 2^32
test1
HD

mg /testnamespace/1 v c N100 f
VA 5 c14194 f4294967296
test1

ms /testnamespace/1 5 C14194 F12884901890 # (3 * 2^32 + 2)
test9
HD

mg /testnamespace/1 v c N100 f
VA 5 c16803 f12884901890
test9

ms /testnamespace/1 4 C16803 F18446744073709551615 # 2^64 - 1
data
HD

mg /testnamespace/1 v c N100 f
VA 4 c17919 f18446744073709551615
data

ms /testnamespace/1 3 C17919 F18446744073709551616 # 2^64
abc
CLIENT_ERROR bad command line format

mg /testnamespace/1 v c N100 f
VA 4 c17919 f18446744073709551615
data
```

Let me know if there's anything more you'd like me to test!

**Comment by dormando** [comment]
If you're confident in it I'll merge it. ready to go?

**Comment by FinnitoProductions** [comment]
All good on our end, ready to merge. Thanks so much @dormando!

**Comment by dormando** [comment]
released in 1.6.22

**Pull request closed without merging**
