### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mkatiyar**
Hi,

This is a pull request for some cleanup code.

git log --stat
=============
commit b31126bfb3860821861a8892380b07b4aecb6d26 (HEAD -> cleanup, origin/cleanup)
Author: Manish Katiyar <mkatiyar@gmail.com>
Date:   Fri Dec 29 08:57:33 2017 -0800

    Add a helper routine assoc_find_item() instead of repetitive code.
    
    Signed-off-by: Manish Katiyar <mkatiyar@gmail.com>

 assoc.c | 43 +++++++++++++++++--------------------------
 1 file changed, 17 insertions(+), 26 deletions(-)

commit 1e10124ac56d6e27f3111e00e7ea1bcb7206193b
Author: Manish Katiyar <mkatiyar@gmail.com>
Date:   Thu Dec 28 09:20:20 2017 -0800

    Rename 'stats' to 'status' for readability.
    
    Signed-off-by: Manish Katiyar <mkatiyar@gmail.com>

 timedrun.c | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

Thanks -
Manish

### CODE REVIEW

**Comment by dormando** [comment]
Hey,

I've dropped the ball a few times on this :( I did merge the stats -> status change since that one makes sense.

I ran the assoc.c change through mc-crusher and found it causes a ~2% performance regression. Since the only benefit is slightly cleaner code, I'm afraid I have to reject that one :( Retested it a bunch of times and it's consistently about that much slower.

not honestly sure how to speed it up offhand, other than changing it to a define, which isn't that much cleaner in the end :/

I appreciate the diffs though! sorry again about losing them on the mailing list.

**Comment by mkatiyar** [comment]
On Mon, Feb 19, 2018, 2:30 PM dormando <notifications@github.com> wrote:

> Hey,
>
> I've dropped the ball a few times on this :( I did merge the stats ->
> status change since that one makes sense.
>
> I ran the assoc.c change through mc-crusher and found it causes a ~2%
> performance regression. Since the only benefit is slightly cleaner code,
> I'm afraid I have to reject that one :( Retested it a bunch of times and
> it's consistently about that much slower.
>
> not honestly sure how to speed it up offhand, other than changing it to a
> define, which isn't that much cleaner in the end :/
>
> I appreciate the diffs though! sorry again about losing them on the
> mailing list.
>

Hi Dormando,

No problem. Appreciate your feedback and thanks for accepting the other
patch.

Thanks -
Manish

**Comment by dormando** [comment]
Thanks for being cool about it :)

I'm honestly curious as to why it's slower, but given how short the code is (and that it's supposed to inline/etc), figuring it out would take more time than I have for it. It's easier to do cleanup work on sections of the code further removed from the core :)

**Comment by mkatiyar** [comment]
On Tue, Feb 20, 2018, 1:42 AM dormando <notifications@github.com> wrote:

> Thanks for being cool about it :)
>
> I'm honestly curious as to why it's slower, but given how short the code
> is (and that it's supposed to inline/etc), figuring it out would take more
> time than I have for it. It's easier to do cleanup work on sections of the
> code further removed from the core :)
>
Hi Dormando,

My suspicion is an extra cache miss due to pointer dereference. Are there
any docs on the mc-crusher that you ran. I would like to dig this further.

Thanks -
Manish

**Comment by dormando** [comment]
went out in 1.5.6

**Pull request closed without merging**
