### PR TITLE
whitespaces test getting perl interpreter from env instead

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by dormando** [comment]
Thanks!

What does this fix, exactly? None of the other scripts use the env perl either.

**Comment by devnexen** [comment]
because the perl interpreter is not necessarily in /usr/bin :-)

**Comment by dormando** [comment]
I think I'm going to give this a rare not merge? There're like a hundred+ places with /usr/bin/perl and I kinda don't want just a few of them to be env perl. that's asking for confusion :)

**Comment by devnexen** [comment]
ah ok was just fixing what was necessary maybe other places are more accessory anyway are they external tools ?

**Comment by dormando** [comment]
all of t/*, version.pl, etc. used in build and test stuff.

**Comment by dormando** [comment]
what platform do you have that this even broke on, btw? I have a bunch of buildbots and never seen this, not even on mac

**Comment by devnexen** [comment]
freebsd

**Comment by dormando** [comment]
13? I have a 12 builder and it's never complained (but maybe I'm not running the scripts in the same way?)

**Comment by devnexen** [comment]
most likely because on freebsd the perl interpreter is in /usr/local/bin (from ports)

**Comment by dormando** [comment]
indeed.. my 12 is like that. I guess the only places perl is actually called in the normal build routine is using env perl. Though I thought ages ago version.pl was being called on fbsd builders.

either way, I get it now. Sorry for the extra poking :)

**Comment by dormando** [comment]
released in 1.6.17

**Pull request closed without merging**
