### PR TITLE
Add a command to dump keys for memcached-tool

### PR DESCRIPTION
**Pull request by junjihashimoto**
For profile and debugging, we need a command to look only at the list of keys and their size.

### CODE REVIEW

**Comment by dormando** [comment]
Thanks!

**Comment by junjihashimoto** [comment]
@dormando 
Thank you for your reply.
What should I do to move forward?

**Comment by dormando** [comment]
Sorry for the delay. I'll probably merge it soon.

**Comment by dormando** [comment]
released in 1.6.16

**Comment by junjihashimoto** [comment]
Thank you for your help!

**Pull request closed without merging**
