### PR TITLE
crc32 update adaptation from the author, mostly about

### PR DESCRIPTION
**Pull request by devnexen**
fixing inline assembly.

### CODE REVIEW

**Comment by dormando** [comment]
thanks!

**Comment by dormando** [comment]
What's your canonical source for this file? I see he seems to have two online, with different versioning and one updated more recently than this.

I feel like this is from the brotli source code but  I can't remember offhand.

**Comment by devnexen** [comment]
It is ; but the changes are from [the author himself.](https://github.com/madler/brotli/commit/46ecea69a993a7ebd2de4a60ae6042d31e26213f)

**Comment by dormando** [comment]
Released in 1.6.21

**Pull request closed without merging**
