### PR TITLE
Added sanity check for maximum connections setting

### PR DESCRIPTION
**Pull request by sergiocarlosmorales**

### CODE REVIEW

**Comment by sergiocarlosmorales** [comment]
If a negative number is specified, the error message may not be useful, so provide an explicit message about what is wrong.

$ ./memcached -c -1
failed to set rlimit for open files. Try starting as root or requesting smaller maxconns value.

**Comment by dormando** [comment]
Probably a good idea. Thanks :)

**Comment by jakesyl** [comment]
:+1:

**Comment by thedrow** [comment]
Should this be merged?

**Comment by sergiocarlosmorales** [comment]
I hope so, I've been tracking another pull request too which is ready: https://github.com/memcached/memcached/pull/130
I assume Alan is a busy man, ping @dormando

**Comment by dormando** [comment]
I'm really sorry :( I've been busy, and my first priority is fixing the wiki. I'll get to this as soon as I can.

**Comment by sergiocarlosmorales** [comment]
no biggie, if you need any help even with fixing the wiki let us know or send me a message or whatever and I can pitch in too. thanks for your work!

**Comment by dormando** [comment]
Thanks! Wiki's been updated (would take patches for anything I missed or needs updating). This is now pushed to the 'next' branch and will go out in the next release.

Any other bugs you want to work on? :)

**Pull request closed without merging**
