### PR TITLE
Check if memory is allocated

### PR DESCRIPTION
**Pull request by klebertarcisio**
Hi everyone,

I think we need to check if memory is really allocated before use it.

Regards

### CODE REVIEW

**Comment by dormando** [comment]
Hey,

Thanks! I have a couple issues here:

1) Since this is just the testapp I don't think this is strictly necessary. It won't be invoked while under high memory pressure :)
2) The code style seems a bit off.
3) Doesn't actually pass the test suite: whitespace.t is failing.

So I'll probably pass on this, but for future reference please run/check the test output on your own first :)

**Comment by klebertarcisio** [comment]
Hi @dormando, 
Thanks for the feedback.
I removed some whitespaces.
Regards

**Comment by dormando** [comment]
squashed and merged for next, thanks!

**Comment by dormando** [comment]
released in 1.6.9!

**Pull request closed without merging**
