### PR TITLE
Further increase systemd service hardening

### PR DESCRIPTION
**Pull request by candrews**
Disable use of namespaces, control groups, addresses families that aren't used, kernel module loading, and setting of kernel tunables.

### CODE REVIEW

**Comment by dormando** [comment]
Apparently one of the recent systemd updates broke increasing maxconns: https://github.com/memcached/memcached/issues/218 - would you mind taking a look?

**Comment by candrews** [comment]
@dormando looked and provided information.

**Comment by candrews** [comment]
Particularly given the recent CVE and interest in such hardening by distros such as Fedora https://lwn.net/SubscriberLink/709755/a3b534d94fc57157/ , can this PR please be merged? (Or if a change is necessary, or problem identified, please let me know so I can address it)

**Comment by dormando** [comment]
It's already in the next branch. I just haven't cut a release yet.

**Comment by dormando** [comment]
released in 1.4.34

**Pull request closed without merging**
