### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by dormando** [comment]
Looks like you do a lot of spelling fixes across repos. Are you a bot or a peruser of codebases? :)

**Comment by jsoref** [comment]
I'm not a bot. I tend to look into projects I either use, have used, or am considering using. This project is in that final category.

I do use a script, but I have to pick the corrections on a per misspelled word basis.

**Comment by dormando** [comment]
Hey,

Sorry it took me a while to come back to this. I'm not going to merge it as a bunch of tiny commits since people have used that to inflate commit statistics in the past. If you're interested in merging, would you mind squashing and rebasing against 'next'?

thanks!

**Comment by jsoref** [comment]
@dormando: done.

Note that it is *much* easier for me to rebase individual fixes than it is a collapsed commit, which is why I submit changes as individual things. It also makes it easier for me to handle things like "we're en-GB, don't change us to en-US" or "X is an API" or "Y is an intentional misspelling that we need for <insert whatever reason>".

I don't care about statistics, I'm happy to collapse changes once a project has indicated it will take them. -- As you've noted, I've contributed to more than enough projects that it really doesn't matter at this point.

**Comment by dormando** [comment]
I totally understand; I usually make a bunch of commits and collapse later. I just prefer that collapsing at the end where possible.

I've merged this for the next release. I really make an impressive amount of typos... It's nice to get all of these at once, since I tend to get random one-off spelling fixes every month anyway. thanks!

**Comment by jsoref** [comment]
For reference, this is now: 79e35287df4cd9e410c3a160c2552ea40a335e2c

**Pull request closed without merging**
