### PR TITLE
Fix SASL_CB_GETCONF(PATH) detection

### PR DESCRIPTION
**Pull request by thatsafunnyname**
Fix for https://github.com/memcached/memcached/issues/365
On RHEL(5|6|7) the name of the defined constant in sasl.h is SASL_CB_GETCONFPATH and not SASL_CB_GETCONF, this adds support for HAVE_SASL_CB_GETCONFPATH in configure.ac and then uses it in sasl_defs.c

### CODE REVIEW

**Comment by dormando** [comment]
nice, thanks! looks good, I'll test it and merge when I get a chance

**Comment by dormando** [comment]
seems to work, I've staged it for the next release! if you want bonus points, reviewing the related sasl tests and improving the wiki docs around sasl are great things to do :)

**Comment by thatsafunnyname** [comment]
Thanks.  I can improve https://github.com/memcached/memcached/wiki/SASLHowto if you can grant me access to edit it.

**Comment by dormando** [comment]
I invited you to an org team, which has 'read' access on memcached.. which I think gives you wiki edit access. give it a shot?

**Comment by dormando** [comment]
hmm... I'll have to try again. Just poked through and I swear the docs said 'read' access to a repo from a team member would allow editing the wiki... you can also just write up a markdown page into gist to get things started. :/ sorry, I have to be a bit careful with write access.

**Comment by thatsafunnyname** [comment]
No problem.  I created:  https://gist.github.com/thatsafunnyname/e76cd73831ed43315d3c23c9d83d1f2e

**Comment by dormando** [comment]
updated, thanks!

**Comment by dormando** [comment]
released in 1.5.7

**Pull request closed without merging**
