### PR TITLE
change fprintf to use unsigned format specifier

### PR DESCRIPTION
**Pull request by rmccullagh**

### CODE REVIEW

**Comment by dormando** [comment]
Thanks! How'd you find this? By code audit I assume? Don't think sid could ever get large enough to cause a bug there.

Still good to have it be correct. I rewrote the commit message to be clear as to which system it touched.

**Comment by rmccullagh** [comment]
@dormando I usually look at all the pull requests, and see if I can spot anything that may have been missed.

**Comment by dormando** [comment]
awww :) That's super nice. You should drop +1's somewhere so I can tell someone's listening.

Development speed will be a bit faster for a little while at least, fwiw.

**Comment by rmccullagh** [comment]
No problem. This is probably my favorite piece of software :) I will! 

That's good to hear. I'm still learning the internals and I hope to provide more contributions as time goes on.

**Comment by dormando** [comment]
If you're interested in contributing feel free to stay in contact (via e-mail/IRC/etc) and ask questions. I can also parcel out small tasks and specific reviews. would be great to get a few people up to speed while I have time.

**Comment by rmccullagh** [comment]
@dormando absolutely. i would be interested in learning about what work needs to be done and what needs to be reviewed. My email can be found in the commits I believe. Or If you want me to email you first, I can, I just don't see your mail address.

-Ryan

**Pull request closed without merging**
