### PR TITLE
ECONNRESET fix proposal for Darwin.

### PR DESCRIPTION
**Pull request by devnexen**
forc+exec is somewhat a bit buggy under Darwin, prefering posix_spawn
here instead.

### CODE REVIEW

**Comment by dormando** [comment]
Can you expand on what's happening and why this change fixes it? Makes me suspicious to see that fork/exec doesn't work.

**Comment by devnexen** [comment]
I noted I got ECONNRESET errors with connections for read operations at least leading to abort. fork under Mac is known to be not fully working as expected/being buggy unless putting quite some workaround while posix_spawn arrange the situation in this area.

**Comment by dormando** [comment]
Almost all of the testapp.c tests are redundant, I'm pretty sure: https://github.com/memcached/memcached/issues/674 - might want to do this in favor of further hacking it up. Would be nice if testapp pivoted to actual unit tests and we kept the integration/end to end tests all in perl.

**Comment by dormando** [comment]
I was fiddling with a Darwin machine over the weekend and didn't get this to happen; is there anything I need to do to reproduce?

**Comment by devnexen** [comment]
Do you get at least the abort cases ?

**Comment by dormando** [comment]
paste an example? What're your `./configure` arguments? Test suite seems to pass without any errors for me.

**Comment by dormando** [comment]
This is on catalina and I haven't tried all of the configure args yet.

**Comment by devnexen** [comment]
ah right because you re testing next branch maybe ? indeed it seems works better.

**Comment by dormando** [comment]
Ah yeah; I'm on next. so I guess that other fix fixes... this one too? Or I can't repro anymore.

**Comment by devnexen** [comment]
likely yes :)

**Comment by dormando** [comment]
Closing this out. We can re-open and re-try if we have a .. re-production again :)

Thanks for the submission, as always!

**Pull request closed without merging**
