### PR TITLE
Metaget support

### PR DESCRIPTION
**Pull request by anatale**
Adding support for metaget & metaget stats

### CODE REVIEW

**Comment by anatale** [comment]
Hi @dormando, do you have any feedback for this PR?  Thanks Alex

**Comment by tharanga** [comment]
+1 @anatale. This is a useful feature for one of our use cases. Can we extends this to include more metadata such as recent access time, size of data (very useful) and flags? May be you can create an issue and I can add more details. 
It's great to have the multi-key mget support, but that could be a follow-up PR.

**Comment by dormando** [comment]
Yeah, definitely not implemented this way. I'm thinking it through:

1) ascii command, but using wbuf and faster printouts. should use a format like lru_crawler metadump, but also maybe a binary gettable version from ascii.
2) binprot, using extra fields and keeping the extras in binary.

These aren't too hard but I've always had a huge fear of them since people will end up relying on internal information. Also, if we don't provide optimized commands people will shoot themselves in the foot. basically a couple problems:

- if the internals ever change, these commands probably need to, so the format should be flexible or extensible.
- which means it probably can't be fast. if it can't be fast, I'll wake up one day with some huge user who does 100% metagets and is irate.

I'll maybe track this in a separate issue.

**Comment by dormando** [comment]
closing in favor of: https://github.com/memcached/memcached/pull/484

**Pull request closed without merging**
